# Generated by Django 5.2.5 on 2025-08-24 18:37

import bookings.models
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_enable_btree_gist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='exclude_overlapping_bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), expressions=[(bookings.models.TsTzRange('start_at', 'end_at'), '&&'), (models.F('room_id'), '=')], name='exclude_overlapping_bookings'),
        ),
    ]
